
// USER REGISTER
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// USER LOGIN 
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// USER LOGIN 
export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";

export const SET_USER = "SET_USER";
// export const SAVE_USER = "SAVE_USER";


// USER LOGOUT
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


// blogs
export const LOAD_BLOGS = "LOAD_BLOGS";
export const ADD_BLOGS = "ADD_BLOGS";
export const REMOVE_BLOGS = "REMOVE_BLOGS";

// categories
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";

//FILTER
export const SORT_BY_CATEGORY = "SORT_BY_CATEGORY";